// <auto-generated />
using System;
using AnalisePlanosSaude.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalisePlanosSaude.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716133531_PersistirOperadoraTipoTabelaPlano")]
    partial class PersistirOperadoraTipoTabelaPlano
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.Analise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<string>("IdadesJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("MensagemCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("PrioridadesJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ResumoCorretor")
                        .HasColumnType("longtext");

                    b.Property<string>("ScriptCorretor")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Analises", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.AnaliseLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnaliseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConteudoPagina")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DadosColetadosJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("AnaliseId");

                    b.ToTable("AnaliseLinks", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoAnalise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DatasetJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<string>("FaixasUtilizadasJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("HashSimulacao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("IdadesJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("LinkOriginal")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("MensagemWhatsApp")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("PrioridadesJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ResumoCorretor")
                        .HasColumnType("longtext");

                    b.Property<string>("ScriptCorretor")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SimulacaoColetaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("HashSimulacao");

                    b.HasIndex("SimulacaoColetaId");

                    b.ToTable("SimulacoesAnalises", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoAtualizacaoJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiffJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxTentativas")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("SimulacaoColetaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int");

                    b.Property<int?>("VersaoGerada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoColetaId");

                    b.HasIndex("Status", "CriadoEm");

                    b.ToTable("SimulacoesAtualizacoesJobs", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoColeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndpointPrincipal")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("EndpointRede")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<string>("HashSimulacao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("JsonPrincipal")
                        .HasColumnType("longtext");

                    b.Property<string>("JsonRede")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("UrlOriginal")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("HashSimulacao");

                    b.ToTable("SimulacoesColetas", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoColetaVersao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiffJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashConteudo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("JsonPrincipal")
                        .HasColumnType("longtext");

                    b.Property<string>("JsonRede")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SimulacaoColetaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HashConteudo");

                    b.HasIndex("SimulacaoColetaId", "Versao")
                        .IsUnique();

                    b.ToTable("SimulacoesColetasVersoes", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxTentativas")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SimulacaoColetaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoColetaId", "Tipo")
                        .IsUnique();

                    b.HasIndex("Status", "CriadoEm");

                    b.ToTable("SimulacoesJobs", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPlano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Acomodacao")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DadosJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Operadora")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("PlanoIdExterno")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("SimulacaoColetaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipoTabela")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoColetaId", "PlanoIdExterno")
                        .IsUnique();

                    b.ToTable("SimulacoesPlanos", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPlanoVersao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Acomodacao")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("DadosJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Operadora")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("PlanoIdExterno")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("SimulacaoColetaVersaoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipoTabela")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoColetaVersaoId", "PlanoIdExterno");

                    b.ToTable("SimulacoesPlanosVersoes", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPrestador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("EspecialidadesJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SimulacaoPlanoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TextoEvidencia")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoPlanoId");

                    b.HasIndex("SimulacaoPlanoId", "Tipo");

                    b.ToTable("SimulacoesPrestadores", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPrestadorVersao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("EspecialidadesJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SimulacaoPlanoVersaoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TextoEvidencia")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoPlanoVersaoId");

                    b.HasIndex("SimulacaoPlanoVersaoId", "Tipo");

                    b.ToTable("SimulacoesPrestadoresVersoes", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoValorFaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("IdadeMax")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeMin")
                        .HasColumnType("int");

                    b.Property<Guid>("SimulacaoPlanoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoPlanoId");

                    b.ToTable("SimulacoesValoresFaixa", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoValorFaixaVersao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("IdadeMax")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeMin")
                        .HasColumnType("int");

                    b.Property<Guid>("SimulacaoPlanoVersaoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoPlanoVersaoId");

                    b.ToTable("SimulacoesValoresFaixaVersoes", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.AnaliseLink", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.Analise", "Analise")
                        .WithMany("Links")
                        .HasForeignKey("AnaliseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analise");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoAnalise", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoColeta", "SimulacaoColeta")
                        .WithMany()
                        .HasForeignKey("SimulacaoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoColeta");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoAtualizacaoJob", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoColeta", "SimulacaoColeta")
                        .WithMany("Atualizacoes")
                        .HasForeignKey("SimulacaoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoColeta");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoColetaVersao", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoColeta", "SimulacaoColeta")
                        .WithMany("Versoes")
                        .HasForeignKey("SimulacaoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoColeta");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoJob", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoColeta", "SimulacaoColeta")
                        .WithMany("Jobs")
                        .HasForeignKey("SimulacaoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoColeta");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPlano", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoColeta", "SimulacaoColeta")
                        .WithMany("Planos")
                        .HasForeignKey("SimulacaoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoColeta");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPlanoVersao", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoColetaVersao", "SimulacaoColetaVersao")
                        .WithMany("Planos")
                        .HasForeignKey("SimulacaoColetaVersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoColetaVersao");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPrestador", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoPlano", "SimulacaoPlano")
                        .WithMany("Prestadores")
                        .HasForeignKey("SimulacaoPlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoPlano");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPrestadorVersao", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoPlanoVersao", "SimulacaoPlanoVersao")
                        .WithMany("Prestadores")
                        .HasForeignKey("SimulacaoPlanoVersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoPlanoVersao");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoValorFaixa", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoPlano", "SimulacaoPlano")
                        .WithMany("ValoresFaixa")
                        .HasForeignKey("SimulacaoPlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoPlano");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoValorFaixaVersao", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.SimulacaoPlanoVersao", "SimulacaoPlanoVersao")
                        .WithMany("ValoresFaixa")
                        .HasForeignKey("SimulacaoPlanoVersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacaoPlanoVersao");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.Analise", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoColeta", b =>
                {
                    b.Navigation("Atualizacoes");

                    b.Navigation("Jobs");

                    b.Navigation("Planos");

                    b.Navigation("Versoes");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoColetaVersao", b =>
                {
                    b.Navigation("Planos");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPlano", b =>
                {
                    b.Navigation("Prestadores");

                    b.Navigation("ValoresFaixa");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.SimulacaoPlanoVersao", b =>
                {
                    b.Navigation("Prestadores");

                    b.Navigation("ValoresFaixa");
                });
#pragma warning restore 612, 618
        }
    }
}
