// <auto-generated />
using System;
using AnalisePlanosSaude.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalisePlanosSaude.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.Analise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<string>("IdadesJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("MensagemCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("PrioridadesJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ResumoCorretor")
                        .HasColumnType("longtext");

                    b.Property<string>("ScriptCorretor")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Analises", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.AnaliseLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnaliseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConteudoPagina")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DadosColetadosJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("AnaliseId");

                    b.ToTable("AnaliseLinks", (string)null);
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.AnaliseLink", b =>
                {
                    b.HasOne("AnalisePlanosSaude.Api.Entities.Analise", "Analise")
                        .WithMany("Links")
                        .HasForeignKey("AnaliseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analise");
                });

            modelBuilder.Entity("AnalisePlanosSaude.Api.Entities.Analise", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
